<Project>
  <PropertyGroup>
    <MicrosoftDotNetXliffTasksVersion>10.0.0-beta.26371.2</MicrosoftDotNetXliffTasksVersion>
    <ErrorOnOutOfDateXlf>false</ErrorOnOutOfDateXlf>
    <UpdateXlfOnBuild>false</UpdateXlfOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Language)' == 'VB' or '$(MSBuildProjectExtension)' == '.vbproj'">
    <MyType>Empty</MyType>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>On</OptionStrict>
    <RemoveIntegerChecks>true</RemoveIntegerChecks>
    <VBRuntime Condition="'$(MSBuildProjectName)' == 'Microsoft.CodeAnalysis.VisualBasic'">Embed</VBRuntime>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Microsoft.CodeAnalysis' or '$(MSBuildProjectName)' == 'Microsoft.CodeAnalysis.VisualBasic' or '$(MSBuildProjectName)' == 'Microsoft.CodeAnalysis.Scripting' or '$(MSBuildProjectName)' == 'Microsoft.CodeAnalysis.VisualBasic.Scripting'">
    <PackageReference Include="Microsoft.DotNet.XliffTasks" Version="$(MicrosoftDotNetXliffTasksVersion)" PrivateAssets="all" />
  </ItemGroup>
</Project>
