//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeAnalysisResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeAnalysisResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.CodeAnalysisResources", typeof(CodeAnalysisResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Absolute path expected. 的本地化字符串。
        /// </summary>
        internal static string AbsolutePathExpected {
            get {
                return ResourceManager.GetString("AbsolutePathExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All analyzers have enabled concurrent execution. 的本地化字符串。
        /// </summary>
        internal static string AllAnalyzersConcurrentMessage {
            get {
                return ResourceManager.GetString("AllAnalyzersConcurrentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzer Driver Failure 的本地化字符串。
        /// </summary>
        internal static string AnalyzerDriverFailure {
            get {
                return ResourceManager.GetString("AnalyzerDriverFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzer driver threw an exception of type &apos;{0}&apos; with message &apos;{1}&apos;.
        ///{2} 的本地化字符串。
        /// </summary>
        internal static string AnalyzerDriverThrows {
            get {
                return ResourceManager.GetString("AnalyzerDriverThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time (s) 的本地化字符串。
        /// </summary>
        internal static string AnalyzerExecutionTimeColumnHeader {
            get {
                return ResourceManager.GetString("AnalyzerExecutionTimeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzer 的本地化字符串。
        /// </summary>
        internal static string AnalyzerNameColumnHeader {
            get {
                return ResourceManager.GetString("AnalyzerNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total analyzer execution time: {0} seconds. 的本地化字符串。
        /// </summary>
        internal static string AnalyzerTotalExecutionTime {
            get {
                return ResourceManager.GetString("AnalyzerTotalExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must either be &apos;default&apos; or have the same length as {1}. 的本地化字符串。
        /// </summary>
        internal static string AnonymousTypeArgumentCountMismatch2 {
            get {
                return ResourceManager.GetString("AnonymousTypeArgumentCountMismatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} and {1} must have the same length. 的本地化字符串。
        /// </summary>
        internal static string AnonymousTypeMemberAndNamesCountMismatch2 {
            get {
                return ResourceManager.GetString("AnonymousTypeMemberAndNamesCountMismatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument cannot have a null element. 的本地化字符串。
        /// </summary>
        internal static string ArgumentElementCannotBeNull {
            get {
                return ResourceManager.GetString("ArgumentElementCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 assembly 的本地化字符串。
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly must have at least one module. 的本地化字符串。
        /// </summary>
        internal static string AssemblyMustHaveAtLeastOneModule {
            get {
                return ResourceManager.GetString("AssemblyMustHaveAtLeastOneModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The assembly containing type &apos;{0}&apos; references .NET Framework, which is not supported. 的本地化字符串。
        /// </summary>
        internal static string AssemblyReferencesNetFramework {
            get {
                return ResourceManager.GetString("AssemblyReferencesNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly signing not supported. 的本地化字符串。
        /// </summary>
        internal static string AssemblySigningNotSupported {
            get {
                return ResourceManager.GetString("AssemblySigningNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 attribute 的本地化字符串。
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal built-in operator name &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string BadBuiltInOps1 {
            get {
                return ResourceManager.GetString("BadBuiltInOps1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported built-in operator: {0} 的本地化字符串。
        /// </summary>
        internal static string BadBuiltInOps2 {
            get {
                return ResourceManager.GetString("BadBuiltInOps2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; was not a valid built-in operator name 的本地化字符串。
        /// </summary>
        internal static string BadBuiltInOps3 {
            get {
                return ResourceManager.GetString("BadBuiltInOps3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t alias a module. 的本地化字符串。
        /// </summary>
        internal static string CannotAliasModule {
            get {
                return ResourceManager.GetString("CannotAliasModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t create a reference to a module. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateReferenceToModule {
            get {
                return ResourceManager.GetString("CannotCreateReferenceToModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t create a reference to a submission. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateReferenceToSubmission {
            get {
                return ResourceManager.GetString("CannotCreateReferenceToSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t embed interop types from module. 的本地化字符串。
        /// </summary>
        internal static string CannotEmbedInteropTypesFromModule {
            get {
                return ResourceManager.GetString("CannotEmbedInteropTypesFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot target net module when emitting ref assembly. 的本地化字符串。
        /// </summary>
        internal static string CannotTargetNetModuleWhenEmittingRefAssembly {
            get {
                return ResourceManager.GetString("CannotTargetNetModuleWhenEmittingRefAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t create a module reference to an assembly. 的本地化字符串。
        /// </summary>
        internal static string CantCreateModuleReferenceToAssembly {
            get {
                return ResourceManager.GetString("CantCreateModuleReferenceToAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t create a metadata reference to an assembly without location. 的本地化字符串。
        /// </summary>
        internal static string CantCreateReferenceToAssemblyWithoutLocation {
            get {
                return ResourceManager.GetString("CantCreateReferenceToAssemblyWithoutLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t create a metadata reference to a dynamic assembly. 的本地化字符串。
        /// </summary>
        internal static string CantCreateReferenceToDynamicAssembly {
            get {
                return ResourceManager.GetString("CantCreateReferenceToDynamicAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes must be within bounds of SourceText 的本地化字符串。
        /// </summary>
        internal static string ChangesMustBeWithinBoundsOfSourceText {
            get {
                return ResourceManager.GetString("ChangesMustBeWithinBoundsOfSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The changes must not overlap. 的本地化字符串。
        /// </summary>
        internal static string ChangesMustNotOverlap {
            get {
                return ResourceManager.GetString("ChangesMustNotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the version of an assembly reference is not allowed during debugging: &apos;{0}&apos; changed version to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ChangingVersionOfAssemblyReferenceIsNotAllowedDuringDebugging {
            get {
                return ResourceManager.GetString("ChangingVersionOfAssemblyReferenceIsNotAllowedDuringDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 class 的本地化字符串。
        /// </summary>
        internal static string Class1 {
            get {
                return ResourceManager.GetString("Class1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 resources, assumed to be in COFF object format, have one or more invalid relocation header values. 的本地化字符串。
        /// </summary>
        internal static string CoffResourceInvalidRelocation {
            get {
                return ResourceManager.GetString("CoffResourceInvalidRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 resources, assumed to be in COFF object format, have an invalid section size. 的本地化字符串。
        /// </summary>
        internal static string CoffResourceInvalidSectionSize {
            get {
                return ResourceManager.GetString("CoffResourceInvalidSectionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 resources, assumed to be in COFF object format, have one or more invalid symbol values. 的本地化字符串。
        /// </summary>
        internal static string CoffResourceInvalidSymbol {
            get {
                return ResourceManager.GetString("CoffResourceInvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 resources, assumed to be in COFF object format, are missing one or both of sections &apos;.rsrc$01&apos; and &apos;.rsrc$02&apos; 的本地化字符串。
        /// </summary>
        internal static string CoffResourceMissingSection {
            get {
                return ResourceManager.GetString("CoffResourceMissingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The compilation is not available during the pre-compilation phase, so {0} cannot be used as an input to a pre-compilation source output. 的本地化字符串。
        /// </summary>
        internal static string CompilationNotAvailableInPreCompilationPhase {
            get {
                return ResourceManager.GetString("CompilationNotAvailableInPreCompilationPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The compilation references multiple assemblies whose versions only differ in auto-generated build and/or revision numbers. 的本地化字符串。
        /// </summary>
        internal static string CompilationReferencesAssembliesWithDifferentAutoGeneratedVersion {
            get {
                return ResourceManager.GetString("CompilationReferencesAssembliesWithDifferentAutoGeneratedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzer Failure 的本地化字符串。
        /// </summary>
        internal static string CompilerAnalyzerFailure {
            get {
                return ResourceManager.GetString("CompilerAnalyzerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzer &apos;{0}&apos; threw an exception of type &apos;{1}&apos; with message &apos;{2}&apos;.
        ///{3} 的本地化字符串。
        /// </summary>
        internal static string CompilerAnalyzerThrows {
            get {
                return ResourceManager.GetString("CompilerAnalyzerThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 constructor 的本地化字符串。
        /// </summary>
        internal static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delegate 的本地化字符串。
        /// </summary>
        internal static string Delegate1 {
            get {
                return ResourceManager.GetString("Delegate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A DiagnosticDescriptor must have an Id that is neither null nor an empty string nor a string that only contains white space. 的本地化字符串。
        /// </summary>
        internal static string DiagnosticIdCantBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("DiagnosticIdCantBeNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suppress the following diagnostics to disable this analyzer: {0} 的本地化字符串。
        /// </summary>
        internal static string DisableAnalyzerDiagnosticsMessage {
            get {
                return ResourceManager.GetString("DisableAnalyzerDiagnosticsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument contains duplicate analyzer instances. 的本地化字符串。
        /// </summary>
        internal static string DuplicateAnalyzerInstances {
            get {
                return ResourceManager.GetString("DuplicateAnalyzerInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 element is expected 的本地化字符串。
        /// </summary>
        internal static string ElementIsExpected {
            get {
                return ResourceManager.GetString("ElementIsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded texts are only supported when emitting a PDB. 的本地化字符串。
        /// </summary>
        internal static string EmbeddedTextsRequirePdb {
            get {
                return ResourceManager.GetString("EmbeddedTextsRequirePdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedding PDB is not allowed when emitting metadata. 的本地化字符串。
        /// </summary>
        internal static string EmbeddingPdbUnexpectedWhenEmittingMetadata {
            get {
                return ResourceManager.GetString("EmbeddingPdbUnexpectedWhenEmittingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A key in the pathMap is empty. 的本地化字符串。
        /// </summary>
        internal static string EmptyKeyInPathMap {
            get {
                return ResourceManager.GetString("EmptyKeyInPathMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty or invalid file name 的本地化字符串。
        /// </summary>
        internal static string EmptyOrInvalidFileName {
            get {
                return ResourceManager.GetString("EmptyOrInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty or invalid resource name 的本地化字符串。
        /// </summary>
        internal static string EmptyOrInvalidResourceName {
            get {
                return ResourceManager.GetString("EmptyOrInvalidResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit and Continue can&apos;t resume suspended asynchronous method since the corresponding await expression has been deleted 的本地化字符串。
        /// </summary>
        internal static string EncCannotResumeSuspendedAsyncMethod {
            get {
                return ResourceManager.GetString("EncCannotResumeSuspendedAsyncMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit and Continue can&apos;t resume suspended iterator since the corresponding yield return statement has been deleted 的本地化字符串。
        /// </summary>
        internal static string EncCannotResumeSuspendedIteratorMethod {
            get {
                return ResourceManager.GetString("EncCannotResumeSuspendedIteratorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempted to invoke a deleted lambda or local function implementation. This can happen when lambda or local function is deleted while the application is running. 的本地化字符串。
        /// </summary>
        internal static string EncDeletedLambdaInvoked {
            get {
                return ResourceManager.GetString("EncDeletedLambdaInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempted to invoke a deleted method implementation. This can happen when a method is deleted or its name or signature is changed while the application is running. 的本地化字符串。
        /// </summary>
        internal static string EncDeletedMethodInvoked {
            get {
                return ResourceManager.GetString("EncDeletedMethodInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempted to invoke lambda or local function with an unsupported change made while the application is running: {0} 的本地化字符串。
        /// </summary>
        internal static string EncLambdaRudeEdit {
            get {
                return ResourceManager.GetString("EncLambdaRudeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempted to invoke lambda or local function that has an unsupported change to captured variables made while the application is running 的本地化字符串。
        /// </summary>
        internal static string EncLambdaRudeEdit_CapturedVariables {
            get {
                return ResourceManager.GetString("EncLambdaRudeEdit_CapturedVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;end&apos; must not be less than &apos;start&apos;. start=&apos;{0}&apos; end=&apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EndMustNotBeLessThanStart {
            get {
                return ResourceManager.GetString("EndMustNotBeLessThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 enum 的本地化字符串。
        /// </summary>
        internal static string Enum1 {
            get {
                return ResourceManager.GetString("Enum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 event 的本地化字符串。
        /// </summary>
        internal static string Event1 {
            get {
                return ResourceManager.GetString("Event1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception occurred with following context:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionContext {
            get {
                return ResourceManager.GetString("ExceptionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}; file may be locked by {1} 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessage_FileMayBeLockedBy {
            get {
                return ResourceManager.GetString("ExceptionMessage_FileMayBeLockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 field 的本地化字符串。
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found. 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generator 的本地化字符串。
        /// </summary>
        internal static string GeneratorNameColumnHeader {
            get {
                return ResourceManager.GetString("GeneratorNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total generator execution time: {0} seconds. 的本地化字符串。
        /// </summary>
        internal static string GeneratorTotalExecutionTime {
            get {
                return ResourceManager.GetString("GeneratorTotalExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The hintName &apos;{0}&apos; contains an invalid character &apos;{1}&apos; at position {2}. 的本地化字符串。
        /// </summary>
        internal static string HintNameInvalidChar {
            get {
                return ResourceManager.GetString("HintNameInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The hintName &apos;{0}&apos; contains an invalid segment &apos;{1}&apos; at position {2}. 的本地化字符串。
        /// </summary>
        internal static string HintNameInvalidSegment {
            get {
                return ResourceManager.GetString("HintNameInvalidSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The hintName &apos;{0}&apos; of the added source file must be unique within a generator. 的本地化字符串。
        /// </summary>
        internal static string HintNameUniquePerGenerator {
            get {
                return ResourceManager.GetString("HintNameUniquePerGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon stream is not in the expected format. 的本地化字符串。
        /// </summary>
        internal static string IconStreamUnexpectedFormat {
            get {
                return ResourceManager.GetString("IconStreamUnexpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Including private members should not be used when emitting to the secondary assembly output. 的本地化字符串。
        /// </summary>
        internal static string IncludingPrivateMembersUnexpectedWhenEmittingToMetadataPeStream {
            get {
                return ResourceManager.GetString("IncludingPrivateMembersUnexpectedWhenEmittingToMetadataPeStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inconsistent language versions 的本地化字符串。
        /// </summary>
        internal static string InconsistentLanguageVersions {
            get {
                return ResourceManager.GetString("InconsistentLanguageVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inconsistent syntax tree features 的本地化字符串。
        /// </summary>
        internal static string InconsistentSyntaxTreeFeature {
            get {
                return ResourceManager.GetString("InconsistentSyntaxTreeFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;in-memory assembly&gt; 的本地化字符串。
        /// </summary>
        internal static string InMemoryAssembly {
            get {
                return ResourceManager.GetString("InMemoryAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;in-memory module&gt; 的本地化字符串。
        /// </summary>
        internal static string InMemoryModule {
            get {
                return ResourceManager.GetString("InMemoryModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 interface 的本地化字符串。
        /// </summary>
        internal static string Interface1 {
            get {
                return ResourceManager.GetString("Interface1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current assembly: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string InternalsVisibleToCurrentAssembly {
            get {
                return ResourceManager.GetString("InternalsVisibleToCurrentAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printing &apos;InternalsVisibleToAttribute&apos; information for the current compilation and all referenced assemblies. 的本地化字符串。
        /// </summary>
        internal static string InternalsVisibleToHeaderSummary {
            get {
                return ResourceManager.GetString("InternalsVisibleToHeaderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly reference: &apos;{0}&apos;
        ///  Grants IVT to current assembly: {1}
        ///  Grants IVTs to: 的本地化字符串。
        /// </summary>
        internal static string InternalsVisibleToReferencedAssembly {
            get {
                return ResourceManager.GetString("InternalsVisibleToReferencedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     Assembly name: &apos;{0}&apos;
        ///    Public Keys: 的本地化字符串。
        /// </summary>
        internal static string InternalsVisibleToReferencedAssemblyDetails {
            get {
                return ResourceManager.GetString("InternalsVisibleToReferencedAssemblyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional file doesn&apos;t belong to the underlying &apos;CompilationWithAnalyzers&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidAdditionalFile {
            get {
                return ResourceManager.GetString("InvalidAdditionalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid alias. 的本地化字符串。
        /// </summary>
        internal static string InvalidAlias {
            get {
                return ResourceManager.GetString("InvalidAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid assembly name: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidAssemblyName {
            get {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid characters in assembly name 的本地化字符串。
        /// </summary>
        internal static string InvalidCharactersInAssemblyName {
            get {
                return ResourceManager.GetString("InvalidCharactersInAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid compilation options -- submission can&apos;t be signed. 的本地化字符串。
        /// </summary>
        internal static string InvalidCompilationOptions {
            get {
                return ResourceManager.GetString("InvalidCompilationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid content type 的本地化字符串。
        /// </summary>
        internal static string InvalidContentType {
            get {
                return ResourceManager.GetString("InvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid culture name: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidCultureName {
            get {
                return ResourceManager.GetString("InvalidCultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid data at offset {0}: {1}{2}*{3}{4} 的本地化字符串。
        /// </summary>
        internal static string InvalidDataAtOffset {
            get {
                return ResourceManager.GetString("InvalidDataAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reported diagnostic has an ID &apos;{0}&apos;, which is not a valid identifier. 的本地化字符串。
        /// </summary>
        internal static string InvalidDiagnosticIdReported {
            get {
                return ResourceManager.GetString("InvalidDiagnosticIdReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reported diagnostic &apos;{0}&apos; has a source location in file &apos;{1}&apos;, which is not part of the compilation being analyzed. 的本地化字符串。
        /// </summary>
        internal static string InvalidDiagnosticLocationReported {
            get {
                return ResourceManager.GetString("InvalidDiagnosticLocationReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reported diagnostic &apos;{0}&apos; has a source location &apos;{1}&apos; in file &apos;{2}&apos;, which is outside of the given file. 的本地化字符串。
        /// </summary>
        internal static string InvalidDiagnosticSpanReported {
            get {
                return ResourceManager.GetString("InvalidDiagnosticSpanReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suppressed diagnostic ID &apos;{0}&apos; does not match suppressable ID &apos;{1}&apos; for the given suppression descriptor. 的本地化字符串。
        /// </summary>
        internal static string InvalidDiagnosticSuppressionReported {
            get {
                return ResourceManager.GetString("InvalidDiagnosticSuppressionReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid hash. 的本地化字符串。
        /// </summary>
        internal static string InvalidHash {
            get {
                return ResourceManager.GetString("InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid instrumentation kind: {0} 的本地化字符串。
        /// </summary>
        internal static string InvalidInstrumentationKind {
            get {
                return ResourceManager.GetString("InvalidInstrumentationKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid module name specified in metadata module &apos;{0}&apos;: &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidModuleName {
            get {
                return ResourceManager.GetString("InvalidModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node to track is not a descendant of the root. 的本地化字符串。
        /// </summary>
        internal static string InvalidNodeToTrack {
            get {
                return ResourceManager.GetString("InvalidNodeToTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Given operation block does not belong to the current analysis context. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperationBlockForAnalysisContext {
            get {
                return ResourceManager.GetString("InvalidOperationBlockForAnalysisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid output kind for submission. DynamicallyLinkedLibrary expected. 的本地化字符串。
        /// </summary>
        internal static string InvalidOutputKindForSubmission {
            get {
                return ResourceManager.GetString("InvalidOutputKindForSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid public key. 的本地化字符串。
        /// </summary>
        internal static string InvalidPublicKey {
            get {
                return ResourceManager.GetString("InvalidPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid public key token. 的本地化字符串。
        /// </summary>
        internal static string InvalidPublicKeyToken {
            get {
                return ResourceManager.GetString("InvalidPublicKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while loading the included rule set file {0} - {1} 的本地化字符串。
        /// </summary>
        internal static string InvalidRuleSetInclude {
            get {
                return ResourceManager.GetString("InvalidRuleSetInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid size of public key token. 的本地化字符串。
        /// </summary>
        internal static string InvalidSizeOfPublicKeyToken {
            get {
                return ResourceManager.GetString("InvalidSizeOfPublicKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax tree doesn&apos;t belong to the underlying &apos;Compilation&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidTree {
            get {
                return ResourceManager.GetString("InvalidTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter &apos;{0}&apos; must be an &apos;INamedTypeSymbol&apos; or an &apos;IAssemblySymbol&apos;. 的本地化字符串。
        /// </summary>
        internal static string IsSymbolAccessibleBadWithin {
            get {
                return ResourceManager.GetString("IsSymbolAccessibleBadWithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter &apos;{0}&apos; must be a symbol from this compilation or some referenced assembly. 的本地化字符串。
        /// </summary>
        internal static string IsSymbolAccessibleWrongAssembly {
            get {
                return ResourceManager.GetString("IsSymbolAccessibleWrongAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument to &apos;/keepalive&apos; option is not a 32-bit integer. 的本地化字符串。
        /// </summary>
        internal static string KeepAliveIsNotAnInteger {
            get {
                return ResourceManager.GetString("KeepAliveIsNotAnInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments to &apos;/keepalive&apos; option below -1 are invalid. 的本地化字符串。
        /// </summary>
        internal static string KeepAliveIsTooSmall {
            get {
                return ResourceManager.GetString("KeepAliveIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;/keepalive&apos; option is only valid with &apos;/shared&apos; option. 的本地化字符串。
        /// </summary>
        internal static string KeepAliveWithoutShared {
            get {
                return ResourceManager.GetString("KeepAliveWithoutShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested line number {0} must be less than the number of lines {1}. 的本地化字符串。
        /// </summary>
        internal static string LineCannotBeGreaterThanEnd {
            get {
                return ResourceManager.GetString("LineCannotBeGreaterThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata PE stream should not be given when emitting metadata only. 的本地化字符串。
        /// </summary>
        internal static string MetadataPeStreamUnexpectedWhenEmittingMetadataOnly {
            get {
                return ResourceManager.GetString("MetadataPeStreamUnexpectedWhenEmittingMetadataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MetadataReference &apos;{0}&apos; not found to remove. 的本地化字符串。
        /// </summary>
        internal static string MetadataRefNotFoundToRemove1 {
            get {
                return ResourceManager.GetString("MetadataRefNotFoundToRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 method 的本地化字符串。
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method symbol expected 的本地化字符串。
        /// </summary>
        internal static string MethodSymbolExpected {
            get {
                return ResourceManager.GetString("MethodSymbolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roslyn compiler server reports different protocol version than build task. 的本地化字符串。
        /// </summary>
        internal static string MismatchedVersion {
            get {
                return ResourceManager.GetString("MismatchedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing argument for &apos;/keepalive&apos; option. 的本地化字符串。
        /// </summary>
        internal static string MissingKeepAlive {
            get {
                return ResourceManager.GetString("MissingKeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item specified is not the element of a list. 的本地化字符串。
        /// </summary>
        internal static string MissingListItem {
            get {
                return ResourceManager.GetString("MissingListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified token must be a direct element of a SyntaxTokenList (such as a modifier in a list of modifiers). The token cannot be an arbitrary token from the syntax tree. 的本地化字符串。
        /// </summary>
        internal static string MissingTokenListItem {
            get {
                return ResourceManager.GetString("MissingTokenListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 module 的本地化字符串。
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module copy can&apos;t be used to create an assembly metadata. 的本地化字符串。
        /// </summary>
        internal static string ModuleCopyCannotBeUsedToCreateAssemblyMetadata {
            get {
                return ResourceManager.GetString("ModuleCopyCannotBeUsedToCreateAssemblyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module has invalid attributes. 的本地化字符串。
        /// </summary>
        internal static string ModuleHasInvalidAttributes {
            get {
                return ResourceManager.GetString("ModuleHasInvalidAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NOTE: Elapsed time may be less than analyzer execution time because analyzers can run concurrently. 的本地化字符串。
        /// </summary>
        internal static string MultithreadedAnalyzerExecutionNote {
            get {
                return ResourceManager.GetString("MultithreadedAnalyzerExecutionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot be null. 的本地化字符串。
        /// </summary>
        internal static string NameCannotBeNull {
            get {
                return ResourceManager.GetString("NameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot start with whitespace. 的本地化字符串。
        /// </summary>
        internal static string NameCannotStartWithWhitespace {
            get {
                return ResourceManager.GetString("NameCannotStartWithWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name contains invalid characters. 的本地化字符串。
        /// </summary>
        internal static string NameContainsInvalidCharacter {
            get {
                return ResourceManager.GetString("NameContainsInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No analyzers found 的本地化字符串。
        /// </summary>
        internal static string NoAnalyzersFound {
            get {
                return ResourceManager.GetString("NoAnalyzersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A node or token is out of sequence. 的本地化字符串。
        /// </summary>
        internal static string NodeOrTokenOutOfSequence {
            get {
                return ResourceManager.GetString("NodeOrTokenOutOfSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzers that have not enabled concurrent execution: 的本地化字符串。
        /// </summary>
        internal static string NonConcurrentAnalyzersHeader {
            get {
                return ResourceManager.GetString("NonConcurrentAnalyzersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-reported diagnostic with ID &apos;{0}&apos; cannot be suppressed. 的本地化字符串。
        /// </summary>
        internal static string NonReportedDiagnosticCannotBeSuppressed {
            get {
                return ResourceManager.GetString("NonReportedDiagnosticCannotBeSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Given operation has a non-null parent. 的本地化字符串。
        /// </summary>
        internal static string NotARootOperation {
            get {
                return ResourceManager.GetString("NotARootOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing 的本地化字符串。
        /// </summary>
        internal static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value in the pathMap is null. 的本地化字符串。
        /// </summary>
        internal static string NullValueInPathMap {
            get {
                return ResourceManager.GetString("NullValueInPathMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Given operation has a null semantic model. 的本地化字符串。
        /// </summary>
        internal static string OperationHasNullSemanticModel {
            get {
                return ResourceManager.GetString("OperationHasNullSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided operation must not be part of a Control Flow Graph. 的本地化字符串。
        /// </summary>
        internal static string OperationMustNotBeControlFlowGraphPart {
            get {
                return ResourceManager.GetString("OperationMustNotBeControlFlowGraphPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output kind not supported. 的本地化字符串。
        /// </summary>
        internal static string OutputKindNotSupported {
            get {
                return ResourceManager.GetString("OutputKindNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parameter 的本地化字符串。
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDB stream should not be given when embedding PDB into the PE stream. 的本地化字符串。
        /// </summary>
        internal static string PdbStreamUnexpectedWhenEmbedding {
            get {
                return ResourceManager.GetString("PdbStreamUnexpectedWhenEmbedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDB stream should not be given when emitting metadata only. 的本地化字符串。
        /// </summary>
        internal static string PdbStreamUnexpectedWhenEmittingMetadataOnly {
            get {
                return ResourceManager.GetString("PdbStreamUnexpectedWhenEmittingMetadataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PE image doesn&apos;t contain managed metadata. 的本地化字符串。
        /// </summary>
        internal static string PEImageDoesntContainManagedMetadata {
            get {
                return ResourceManager.GetString("PEImageDoesntContainManagedMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous submission has errors. 的本地化字符串。
        /// </summary>
        internal static string PreviousSubmissionHasErrors {
            get {
                return ResourceManager.GetString("PreviousSubmissionHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 property, indexer 的本地化字符串。
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference of type &apos;{0}&apos; is not valid for this compilation. 的本地化字符串。
        /// </summary>
        internal static string ReferenceOfTypeIsInvalid1 {
            get {
                return ResourceManager.GetString("ReferenceOfTypeIsInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference resolver should return readable non-null stream. 的本地化字符串。
        /// </summary>
        internal static string ReferenceResolverShouldReturnReadableNonNullStream {
            get {
                return ResourceManager.GetString("ReferenceResolverShouldReturnReadableNonNullStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource data provider should return non-null stream 的本地化字符串。
        /// </summary>
        internal static string ResourceDataProviderShouldReturnNonNullStream {
            get {
                return ResourceManager.GetString("ResourceDataProviderShouldReturnNonNullStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource stream ended at {0} bytes, expected {1} bytes. 的本地化字符串。
        /// </summary>
        internal static string ResourceStreamEndedUnexpectedly {
            get {
                return ResourceManager.GetString("ResourceStreamEndedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource stream provider should return non-null stream. 的本地化字符串。
        /// </summary>
        internal static string ResourceStreamProviderShouldReturnNonNullStream {
            get {
                return ResourceManager.GetString("ResourceStreamProviderShouldReturnNonNullStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 return 的本地化字符串。
        /// </summary>
        internal static string Return1 {
            get {
                return ResourceManager.GetString("Return1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return type can&apos;t be a value type, pointer, by-ref or open generic type 的本地化字符串。
        /// </summary>
        internal static string ReturnTypeCannotBeValuePointerbyRefOrOpen {
            get {
                return ResourceManager.GetString("ReturnTypeCannotBeValuePointerbyRefOrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return type can&apos;t be void, by-ref or open generic type 的本地化字符串。
        /// </summary>
        internal static string ReturnTypeCannotBeVoidByRefOrOpen {
            get {
                return ResourceManager.GetString("ReturnTypeCannotBeVoidByRefOrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute {0} has an invalid value of {1}. 的本地化字符串。
        /// </summary>
        internal static string RuleSetBadAttributeValue {
            get {
                return ResourceManager.GetString("RuleSetBadAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The rule set file has duplicate rules for &apos;{0}&apos; with differing actions &apos;{1}&apos; and &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string RuleSetHasDuplicateRules {
            get {
                return ResourceManager.GetString("RuleSetHasDuplicateRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The element {0} is missing an attribute named {1}. 的本地化字符串。
        /// </summary>
        internal static string RuleSetMissingAttribute {
            get {
                return ResourceManager.GetString("RuleSetMissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 separator is expected 的本地化字符串。
        /// </summary>
        internal static string SeparatorIsExpected {
            get {
                return ResourceManager.GetString("SeparatorIsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New separator must have the same Language as the separator being replaced. 的本地化字符串。
        /// </summary>
        internal static string SeparatorTokenMustHaveSameLanguage {
            get {
                return ResourceManager.GetString("SeparatorTokenMustHaveSameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New separator must have the same RawKind as the separator being replaced. 的本地化字符串。
        /// </summary>
        internal static string SeparatorTokenMustHaveSameRawKind {
            get {
                return ResourceManager.GetString("SeparatorTokenMustHaveSameRawKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value for argument &apos;/shared:&apos; must not be empty 的本地化字符串。
        /// </summary>
        internal static string SharedArgumentMissing {
            get {
                return ResourceManager.GetString("SharedArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The temporary path for legacy file signing is unavailable. 的本地化字符串。
        /// </summary>
        internal static string SigningTempPathUnavailable {
            get {
                return ResourceManager.GetString("SigningTempPathUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only a single {0} can be registered per generator. 的本地化字符串。
        /// </summary>
        internal static string Single_type_per_generator_0 {
            get {
                return ResourceManager.GetString("Single_type_per_generator_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size has to be positive. 的本地化字符串。
        /// </summary>
        internal static string SizeHasToBePositive {
            get {
                return ResourceManager.GetString("SizeHasToBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SourceText cannot be embedded. Provide encoding or canBeEmbedded=true at construction. 的本地化字符串。
        /// </summary>
        internal static string SourceTextCannotBeEmbedded {
            get {
                return ResourceManager.GetString("SourceTextCannotBeEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SourceText with hintName &apos;{0}&apos; must have an explicit encoding set. 的本地化字符串。
        /// </summary>
        internal static string SourceTextRequiresEncoding {
            get {
                return ResourceManager.GetString("SourceTextRequiresEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The span does not include the end of a line. 的本地化字符串。
        /// </summary>
        internal static string SpanDoesNotIncludeEndOfLine {
            get {
                return ResourceManager.GetString("SpanDoesNotIncludeEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The span does not include the start of a line. 的本地化字符串。
        /// </summary>
        internal static string SpanDoesNotIncludeStartOfLine {
            get {
                return ResourceManager.GetString("SpanDoesNotIncludeStartOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;start&apos; must not be negative 的本地化字符串。
        /// </summary>
        internal static string StartMustNotBeNegative {
            get {
                return ResourceManager.GetString("StartMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream is too long. 的本地化字符串。
        /// </summary>
        internal static string StreamIsTooLong {
            get {
                return ResourceManager.GetString("StreamIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream must be readable. 的本地化字符串。
        /// </summary>
        internal static string StreamMustSupportRead {
            get {
                return ResourceManager.GetString("StreamMustSupportRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream must support read and seek operations. 的本地化字符串。
        /// </summary>
        internal static string StreamMustSupportReadAndSeek {
            get {
                return ResourceManager.GetString("StreamMustSupportReadAndSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream must be writable. 的本地化字符串。
        /// </summary>
        internal static string StreamMustSupportWrite {
            get {
                return ResourceManager.GetString("StreamMustSupportWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 struct 的本地化字符串。
        /// </summary>
        internal static string Struct1 {
            get {
                return ResourceManager.GetString("Struct1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzer &apos;{0}&apos; contains a null descriptor in its &apos;SupportedDiagnostics&apos;. 的本地化字符串。
        /// </summary>
        internal static string SupportedDiagnosticsHasNullDescriptor {
            get {
                return ResourceManager.GetString("SupportedDiagnosticsHasNullDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzer &apos;{0}&apos; contains a null descriptor in its &apos;SupportedSuppressions&apos;. 的本地化字符串。
        /// </summary>
        internal static string SupportedSuppressionsHasNullDescriptor {
            get {
                return ResourceManager.GetString("SupportedSuppressionsHasNullDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnostic &apos;{0}: {1}&apos; was programmatically suppressed by a DiagnosticSuppressor with suppression ID &apos;{2}&apos; and justification &apos;{3}&apos; 的本地化字符串。
        /// </summary>
        internal static string SuppressionDiagnosticDescriptorMessage {
            get {
                return ResourceManager.GetString("SuppressionDiagnosticDescriptorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Programmatic suppression of an analyzer diagnostic 的本地化字符串。
        /// </summary>
        internal static string SuppressionDiagnosticDescriptorTitle {
            get {
                return ResourceManager.GetString("SuppressionDiagnosticDescriptorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A SuppressionDescriptor must have an Id that is neither null nor an empty string nor a string that only contains white space. 的本地化字符串。
        /// </summary>
        internal static string SuppressionIdCantBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("SuppressionIdCantBeNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NOTE: {0} diagnostic suppressors were found. Diagnostic suppressors never run concurrently. 的本地化字符串。
        /// </summary>
        internal static string SuppressorsNonConcurrentCountMessage {
            get {
                return ResourceManager.GetString("SuppressorsNonConcurrentCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows PDB writer doesn&apos;t support SourceLink feature: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SymWriterDoesNotSupportSourceLink {
            get {
                return ResourceManager.GetString("SymWriterDoesNotSupportSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot emit native PDB for method &apos;{0}&apos; because its debug metadata size {1} is over the limit {2}. 的本地化字符串。
        /// </summary>
        internal static string SymWriterMetadataOverLimit {
            get {
                return ResourceManager.GetString("SymWriterMetadataOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows PDB writer doesn&apos;t support deterministic compilation: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SymWriterNotDeterministic {
            get {
                return ResourceManager.GetString("SymWriterNotDeterministic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version of Windows PDB writer is older than required: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SymWriterOlderVersionThanRequired {
            get {
                return ResourceManager.GetString("SymWriterOlderVersionThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax-based providers (e.g. SyntaxProvider, ForAttributeWithMetadataName) cannot be used as inputs to a pre-compilation source output, because the compilation has not yet been built. 的本地化字符串。
        /// </summary>
        internal static string SyntaxProvidersNotAvailableInPreCompilationPhase {
            get {
                return ResourceManager.GetString("SyntaxProvidersNotAvailableInPreCompilationPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If tuple element locations are specified, the number of locations must match the cardinality of the tuple. 的本地化字符串。
        /// </summary>
        internal static string TupleElementLocationCountMismatch {
            get {
                return ResourceManager.GetString("TupleElementLocationCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If tuple element names are specified, the number of element names must match the cardinality of the tuple. 的本地化字符串。
        /// </summary>
        internal static string TupleElementNameCountMismatch {
            get {
                return ResourceManager.GetString("TupleElementNameCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuple element name cannot be an empty string. 的本地化字符串。
        /// </summary>
        internal static string TupleElementNameEmpty {
            get {
                return ResourceManager.GetString("TupleElementNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If tuple element nullable annotations are specified, the number of annotations must match the cardinality of the tuple. 的本地化字符串。
        /// </summary>
        internal static string TupleElementNullableAnnotationCountMismatch {
            get {
                return ResourceManager.GetString("TupleElementNullableAnnotationCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuples must have at least two elements. 的本地化字符串。
        /// </summary>
        internal static string TuplesNeedAtLeastTwoElements {
            get {
                return ResourceManager.GetString("TuplesNeedAtLeastTwoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The underlying type for a tuple must be tuple-compatible. 的本地化字符串。
        /// </summary>
        internal static string TupleUnderlyingTypeMustBeTupleCompatible {
            get {
                return ResourceManager.GetString("TupleUnderlyingTypeMustBeTupleCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; type does not have the expected constructor 的本地化字符串。
        /// </summary>
        internal static string Type0DoesNotHaveExpectedConstructor {
            get {
                return ResourceManager.GetString("Type0DoesNotHaveExpectedConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type must be same as host object type of previous submission. 的本地化字符串。
        /// </summary>
        internal static string TypeMustBeSameAsHostObjectTypeOfPreviousSubmission {
            get {
                return ResourceManager.GetString("TypeMustBeSameAsHostObjectTypeOfPreviousSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type parameter 的本地化字符串。
        /// </summary>
        internal static string TypeParameter {
            get {
                return ResourceManager.GetString("TypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine specific cause of the failure. 的本地化字符串。
        /// </summary>
        internal static string UnableToDetermineSpecificCauseOfFailure {
            get {
                return ResourceManager.GetString("UnableToDetermineSpecificCauseOfFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A node in the list is not of the expected type. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedTypeOfNodeInList {
            get {
                return ResourceManager.GetString("UnexpectedTypeOfNodeInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized resource file format. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedResourceFileFormat {
            get {
                return ResourceManager.GetString("UnrecognizedResourceFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unresolved:  的本地化字符串。
        /// </summary>
        internal static string Unresolved {
            get {
                return ResourceManager.GetString("Unresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument contains an analyzer instance that does not belong to the &apos;Analyzers&apos; for this CompilationWithAnalyzers instance. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedAnalyzerInstance {
            get {
                return ResourceManager.GetString("UnsupportedAnalyzerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reported diagnostic with ID &apos;{0}&apos; is not supported by the analyzer. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedDiagnosticReported {
            get {
                return ResourceManager.GetString("UnsupportedDiagnosticReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported hash algorithm. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedHashAlgorithm {
            get {
                return ResourceManager.GetString("UnsupportedHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reported suppression with ID &apos;{0}&apos; is not supported by the suppressor. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedSuppressionReported {
            get {
                return ResourceManager.GetString("UnsupportedSuppressionReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WindowsRuntime identity can&apos;t be retargetable 的本地化字符串。
        /// </summary>
        internal static string WinRTIdentityCantBeRetargetable {
            get {
                return ResourceManager.GetString("WinRTIdentityCantBeRetargetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global analyzer config section name &apos;{0}&apos; is invalid as it is not an absolute path. Section will be ignored. Section was declared in file: &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string WRN_InvalidGlobalSectionName {
            get {
                return ResourceManager.GetString("WRN_InvalidGlobalSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global analyzer config section name is invalid as it is not an absolute path. Section will be ignored. 的本地化字符串。
        /// </summary>
        internal static string WRN_InvalidGlobalSectionName_Title {
            get {
                return ResourceManager.GetString("WRN_InvalidGlobalSectionName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The diagnostic &apos;{0}&apos; was given an invalid severity &apos;{1}&apos; in the analyzer config file at &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string WRN_InvalidSeverityInAnalyzerConfig {
            get {
                return ResourceManager.GetString("WRN_InvalidSeverityInAnalyzerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid severity in analyzer config file. 的本地化字符串。
        /// </summary>
        internal static string WRN_InvalidSeverityInAnalyzerConfig_Title {
            get {
                return ResourceManager.GetString("WRN_InvalidSeverityInAnalyzerConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple global analyzer config files set the same key &apos;{0}&apos; in section &apos;{1}&apos;. It has been unset. Key was set by the following files: &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        internal static string WRN_MultipleGlobalAnalyzerKeys {
            get {
                return ResourceManager.GetString("WRN_MultipleGlobalAnalyzerKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple global analyzer config files set the same key. It has been unset. 的本地化字符串。
        /// </summary>
        internal static string WRN_MultipleGlobalAnalyzerKeys_Title {
            get {
                return ResourceManager.GetString("WRN_MultipleGlobalAnalyzerKeys_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 References to XML documents are not supported. 的本地化字符串。
        /// </summary>
        internal static string XmlReferencesNotSupported {
            get {
                return ResourceManager.GetString("XmlReferencesNotSupported", resourceCulture);
            }
        }
    }
}
