//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.Scripting {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptingResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.Scripting.ScriptingResources", typeof(ScriptingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Absolute path expected 的本地化字符串。
        /// </summary>
        internal static string AbsolutePathExpected {
            get {
                return ResourceManager.GetString("AbsolutePathExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly &apos;{0}, Version={1}&apos; has already been loaded from &apos;{2}&apos;. A different assembly with the same name and version can&apos;t be loaded: &apos;{3}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AssemblyAlreadyLoaded {
            get {
                return ResourceManager.GetString("AssemblyAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly &apos;{0}&apos; has already been loaded from &apos;{1}&apos;. A different assembly with the same name can&apos;t be loaded unless it&apos;s signed: &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AssemblyAlreadyLoadedNotSigned {
            get {
                return ResourceManager.GetString("AssemblyAlreadyLoadedNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  at {0} : {1} 的本地化字符串。
        /// </summary>
        internal static string AtFileLine {
            get {
                return ResourceManager.GetString("AtFileLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set a constant variable 的本地化字符串。
        /// </summary>
        internal static string CannotSetConstantVariable {
            get {
                return ResourceManager.GetString("CannotSetConstantVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set {0} specific option {1} because the options were already configured for a different language. 的本地化字符串。
        /// </summary>
        internal static string CannotSetLanguageSpecificOption {
            get {
                return ResourceManager.GetString("CannotSetLanguageSpecificOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set a read-only variable 的本地化字符串。
        /// </summary>
        internal static string CannotSetReadOnlyVariable {
            get {
                return ResourceManager.GetString("CannotSetReadOnlyVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t assign &apos;{0}&apos; to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CantAssignTo {
            get {
                return ResourceManager.GetString("CantAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display name or path cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string DisplayNameOrPathCannotBe {
            get {
                return ResourceManager.GetString("DisplayNameOrPathCannotBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected an assembly reference. 的本地化字符串。
        /// </summary>
        internal static string ExpectedAnAssemblyReference {
            get {
                return ResourceManager.GetString("ExpectedAnAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The globals of type &apos;{0}&apos; is not assignable to &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string GlobalsNotAssignable {
            get {
                return ResourceManager.GetString("GlobalsNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global variables passed to a script without a global type 的本地化字符串。
        /// </summary>
        internal static string GlobalVariablesWithoutGlobalType {
            get {
                return ResourceManager.GetString("GlobalVariablesWithoutGlobalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &quot;#help&quot; for more information. 的本地化字符串。
        /// </summary>
        internal static string HelpPrompt {
            get {
                return ResourceManager.GetString("HelpPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard shortcuts:
        ///  Enter         If the current submission appears to be complete, evaluate it.  Otherwise, insert a new line.
        ///  Escape        Clear the current submission.
        ///  UpArrow       Replace the current submission with a previous submission.
        ///  DownArrow     Replace the current submission with a subsequent submission (after having previously navigated backwards).
        ///  Ctrl-C        Exit the REPL.
        ///REPL commands:
        ///  #help         Display help on available commands and key bindings.
        ///Script directiv [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid assembly name 的本地化字符串。
        /// </summary>
        internal static string InvalidAssemblyName {
            get {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid characters in assemblyName 的本地化字符串。
        /// </summary>
        internal static string InvalidCharactersInAssemblyName {
            get {
                return ResourceManager.GetString("InvalidCharactersInAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + additional {0} error 的本地化字符串。
        /// </summary>
        internal static string PlusAdditionalError {
            get {
                return ResourceManager.GetString("PlusAdditionalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + additional {0} errors 的本地化字符串。
        /// </summary>
        internal static string PlusAdditionalErrors {
            get {
                return ResourceManager.GetString("PlusAdditionalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The script requires access to global variables but none were given 的本地化字符串。
        /// </summary>
        internal static string ScriptRequiresGlobalVariables {
            get {
                return ResourceManager.GetString("ScriptRequiresGlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 !&lt;Stack overflow while evaluating object&gt; 的本地化字符串。
        /// </summary>
        internal static string StackOverflowWhileEvaluating {
            get {
                return ResourceManager.GetString("StackOverflowWhileEvaluating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting state was incompatible with script. 的本地化字符串。
        /// </summary>
        internal static string StartingStateIncompatible {
            get {
                return ResourceManager.GetString("StartingStateIncompatible", resourceCulture);
            }
        }
    }
}
