'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("vbichooser.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 ERROR: Incorrect parameter count 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Error_IncorrectParameterCount() As String
            Get
                Return ResourceManager.GetString("Error.IncorrectParameterCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Runtime Error 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Error_RuntimeError() As String
            Get
                Return ResourceManager.GetString("Error.RuntimeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Which runtime framework would you like to use? 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RuntimeSelectionDialog_Content() As String
            Get
                Return ResourceManager.GetString("RuntimeSelectionDialog.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 .NET 8 (Windows Desktop) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RuntimeSelectionDialog_Net() As String
            Get
                Return ResourceManager.GetString("RuntimeSelectionDialog.Net", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 .NET Framework 4.8 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RuntimeSelectionDialog_NetFw() As String
            Get
                Return ResourceManager.GetString("RuntimeSelectionDialog.NetFw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Select Runtime Framework 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RuntimeSelectionDialog_Title() As String
            Get
                Return ResourceManager.GetString("RuntimeSelectionDialog.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Don&apos;t run 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SecurityDialog_Block() As String
            Get
                Return ResourceManager.GetString("SecurityDialog.Block", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Running scripts can potentially harm your computer.
        '''Do not run it if you obtained it from an untrusted source. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SecurityDialog_Content() As String
            Get
                Return ResourceManager.GetString("SecurityDialog.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Run anyway 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SecurityDialog_Run() As String
            Get
                Return ResourceManager.GetString("SecurityDialog.Run", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Security Warning (VB.NET Script) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SecurityDialog_Title() As String
            Get
                Return ResourceManager.GetString("SecurityDialog.Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
